# Form implementation generated from reading ui file 'team_1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(812, 512)
        Form.setStyleSheet("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setMinimumSize(QtCore.QSize(800, 500))
        self.frame_2.setMaximumSize(QtCore.QSize(800, 500))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"    image: url(res/img.png);\n"
"    border-radius: 15;\n"
"    border: 0px solid rgb(255, 255, 255);\n"
"}\n"
"QPushButton {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    background-color:rgba(0, 0, 0, 70);\n"
"    min-width: 80px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-style: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton_18 {\n"
"    min-width: 0px;\n"
"    border: 0px solid rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton#pushButton_19 {\n"
"    min-width: 20px;\n"
"    border: 0px solid rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QTableWidget#tableWidget {\n"
"    background-color: rgba(255, 255, 255, 180)\n"
"}\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_19.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_19.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_19.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(30)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout.addWidget(self.pushButton_19, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_18.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_18.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout.addWidget(self.pushButton_18, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(600, 420))
        self.tableWidget.setMaximumSize(QtCore.QSize(600, 420))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_19.setText(_translate("Form", "🠔"))
        self.pushButton_18.setText(_translate("Form", ""))
